### PR TITLE
Wagtail 5.2

### PR DESCRIPTION
**Pull request by katdom13**
## [Wagtail 5.2 release notes](https://docs.wagtail.org/en/stable/releases/5.2.html)

Upgrade considerations:
- [Adoption of classname convention for MenuItem related classes and hooks
](https://docs.wagtail.org/en/stable/releases/5.2.html#adoption-of-classname-convention-for-menuitem-related-classes-and-hooks)

Other changes:
- Update test matrix to include Wagtail 5.2
- Support tox testing
- Linting

### CODE REVIEW

**Comment by gasman** [comment]
Thanks @katdom13!

What's the motivation for switching our CI setup to tox? As far as I can see, that change results in our Github Actions setup no longer specifying Django / Wagtail versions, so we just end up testing against the latest ones rather than the full range of versions.

**Comment by katdom13** [comment]
Hi @gasman ,
Thanks for taking a look!
I thought that listing the combinations can get very tedious if we were to maintain more Wagtail versions. Plus it would be great if we had some sort of a uniform testing across Wagtail and Torchbox-maintained packages.

Please let me know if you'd prefer to keep the previous testing setup, or if you have any ssuggestions.

**Comment by gasman** [comment]
I think there are a couple of different topics being conflated here:

### Testing a full matrix vs. specifying combinations

Taking the test matrix as defined in tox.ini here:

    py{38,39,310}-django{32,41}-wagtail{41,51,52}-{sqlite,postgresql}
    py311-django41-wagtail{41,51,52}-{sqlite,postgresql}
    py311-django42-wagtail{51,52}-{sqlite,postgresql}

If I've calculated correctly, this gives us 46 test runs in total. (This _isn't_ happening on Github Actions at the moment, because test.yml is misconfigured and is calling `tox` with no arguments, so it's only doing one test run per Python version, using the latest versions of the libraries each time.) This is a waste of resources, and makes the tests take much longer to complete than they need to. If there's a regression from Python 3.8 to 3.9, we can identify that (along with other kinds of regression) by just running `py38-django32-wagtail41-sqlite` and `py39-django41-wagtail51-postgresql` - we don't need 8 test runs for each Python version.

Ultimately this doesn't save us from having to manage the list manually anyway - we still have to adjust the list to leave out invalid combinations. For these reasons, I'm opposed to running against the full matrix.

### Using `tox` vs. just using Github Actions

Given that we're continuing to use Github Actions either way, I don't see what benefit `tox` gives us - it's just repeating the configuration in two places. (Maybe the plan is to _only_ have the configuration in tox.ini, but as mentioned, that's currently broken here, and I can't see how it could work - in order for the test runs to show up individually in the Github Actions UI, rather than just one test runner running everything in sequence, that information has to be in test.yml, doesn't it?)

Either way, let's not try to do multiple things in one PR - please can you open one PR for the 5.2 compatibility fixes, one to add linting, and one for migrating to tox.ini (if you're still interested in pursuing that)?

**Comment by katdom13** [comment]
Hi @gasman ,
Thanks for the feedback above. I will be creating a new PR for now with only the changes for Wagtail 5.2.
Please see https://github.com/torchbox/wagtail-webstories/pull/26

**Pull request closed without merging**
